# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sun May  4 19:39:18 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(934, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(600, 180, 181, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.connect_button = QtGui.QPushButton(self.groupBox_2)
        self.connect_button.setGeometry(QtCore.QRect(10, 40, 171, 27))
        self.connect_button.setObjectName(_fromUtf8("connect_button"))
        self.ref_point_button = QtGui.QPushButton(self.groupBox_2)
        self.ref_point_button.setGeometry(QtCore.QRect(10, 80, 171, 27))
        self.ref_point_button.setObjectName(_fromUtf8("ref_point_button"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(600, 20, 361, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 180, 241, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.timeline = QtGui.QSlider(self.groupBox_3)
        self.timeline.setGeometry(QtCore.QRect(10, 100, 231, 19))
        self.timeline.setOrientation(QtCore.Qt.Horizontal)
        self.timeline.setObjectName(_fromUtf8("timeline"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 180, 110))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cal_state_A = QtGui.QLabel(self.verticalLayoutWidget)
        self.cal_state_A.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.cal_state_A.setObjectName(_fromUtf8("cal_state_A"))
        self.verticalLayout.addWidget(self.cal_state_A)
        self.cal_state_B = QtGui.QLabel(self.verticalLayoutWidget)
        self.cal_state_B.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 4);"))
        self.cal_state_B.setObjectName(_fromUtf8("cal_state_B"))
        self.verticalLayout.addWidget(self.cal_state_B)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cal_00 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.cal_00.setObjectName(_fromUtf8("cal_00"))
        self.gridLayout.addWidget(self.cal_00, 1, 0, 1, 1)
        self.cal_10 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.cal_10.setObjectName(_fromUtf8("cal_10"))
        self.gridLayout.addWidget(self.cal_10, 1, 1, 1, 1)
        self.cal_01 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.cal_01.setObjectName(_fromUtf8("cal_01"))
        self.gridLayout.addWidget(self.cal_01, 0, 0, 1, 1)
        self.cal_11 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.cal_11.setObjectName(_fromUtf8("cal_11"))
        self.gridLayout.addWidget(self.cal_11, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.reset_A = QtGui.QPushButton(self.groupBox)
        self.reset_A.setGeometry(QtCore.QRect(190, 30, 21, 21))
        self.reset_A.setObjectName(_fromUtf8("reset_A"))
        self.reset_B = QtGui.QPushButton(self.groupBox)
        self.reset_B.setGeometry(QtCore.QRect(190, 50, 21, 21))
        self.reset_B.setObjectName(_fromUtf8("reset_B"))
        self.live_radio = QtGui.QRadioButton(self.centralwidget)
        self.live_radio.setGeometry(QtCore.QRect(620, 430, 114, 22))
        self.live_radio.setObjectName(_fromUtf8("live_radio"))
        self.playback_radio = QtGui.QRadioButton(self.centralwidget)
        self.playback_radio.setGeometry(QtCore.QRect(620, 450, 114, 22))
        self.playback_radio.setObjectName(_fromUtf8("playback_radio"))
        self.rec = QtGui.QPushButton(self.centralwidget)
        self.rec.setGeometry(QtCore.QRect(620, 340, 98, 27))
        self.rec.setObjectName(_fromUtf8("rec"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 934, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuWiiMotes = QtGui.QMenu(self.menubar)
        self.menuWiiMotes.setObjectName(_fromUtf8("menuWiiMotes"))
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName(_fromUtf8("menuInfo"))
        self.menuMessung = QtGui.QMenu(self.menubar)
        self.menuMessung.setObjectName(_fromUtf8("menuMessung"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionVerbinden = QtGui.QAction(MainWindow)
        self.actionVerbinden.setObjectName(_fromUtf8("actionVerbinden"))
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName(_fromUtf8("actionBeenden"))
        self.new_project = QtGui.QAction(MainWindow)
        self.new_project.setObjectName(_fromUtf8("new_project"))
        self.load_project = QtGui.QAction(MainWindow)
        self.load_project.setObjectName(_fromUtf8("load_project"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionSpeichern = QtGui.QAction(MainWindow)
        self.actionSpeichern.setObjectName(_fromUtf8("actionSpeichern"))
        self.actionLaden = QtGui.QAction(MainWindow)
        self.actionLaden.setObjectName(_fromUtf8("actionLaden"))
        self.actionCal = QtGui.QAction(MainWindow)
        self.actionCal.setObjectName(_fromUtf8("actionCal"))
        self.menuWiiMotes.addAction(self.actionVerbinden)
        self.menuWiiMotes.addSeparator()
        self.menuWiiMotes.addAction(self.actionBeenden)
        self.menuInfo.addAction(self.actionCal)
        self.menuInfo.addAction(self.actionAbout)
        self.menuMessung.addAction(self.actionExport)
        self.menuMessung.addAction(self.actionSpeichern)
        self.menuMessung.addAction(self.actionLaden)
        self.menubar.addAction(self.menuWiiMotes.menuAction())
        self.menubar.addAction(self.menuMessung.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Konfiguration", None))
        self.connect_button.setText(_translate("MainWindow", "Punkte Verbinden", None))
        self.ref_point_button.setText(_translate("MainWindow", "Referenzpunkt setzen", None))
        self.groupBox.setTitle(_translate("MainWindow", "Eichung", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Messung", None))
        self.cal_state_A.setText(_translate("MainWindow", "WM A nicht kalibriert", None))
        self.cal_state_B.setText(_translate("MainWindow", "WM B nicht kalibriert", None))
        self.cal_00.setText(_translate("MainWindow", "(0,0)", None))
        self.cal_10.setText(_translate("MainWindow", "(1,0)", None))
        self.cal_01.setText(_translate("MainWindow", "(0,1)", None))
        self.cal_11.setText(_translate("MainWindow", "(1,1)", None))
        self.reset_A.setText(_translate("MainWindow", "X", None))
        self.reset_B.setText(_translate("MainWindow", "X", None))
        self.live_radio.setText(_translate("MainWindow", "Live Ansicht", None))
        self.playback_radio.setText(_translate("MainWindow", "Widergabe", None))
        self.rec.setText(_translate("MainWindow", "Aufnehmen", None))
        self.menuWiiMotes.setTitle(_translate("MainWindow", "Datei", None))
        self.menuInfo.setTitle(_translate("MainWindow", "Einstellungen", None))
        self.menuMessung.setTitle(_translate("MainWindow", "Messung", None))
        self.actionVerbinden.setText(_translate("MainWindow", "WiiMotes Verbinden", None))
        self.actionVerbinden.setShortcut(_translate("MainWindow", "C", None))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden", None))
        self.actionBeenden.setShortcut(_translate("MainWindow", "Q", None))
        self.new_project.setText(_translate("MainWindow", "Neue Messung", None))
        self.load_project.setText(_translate("MainWindow", "Messung Laden", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionExport.setText(_translate("MainWindow", "Als CSV exportieren", None))
        self.actionSpeichern.setText(_translate("MainWindow", "Speichern", None))
        self.actionLaden.setText(_translate("MainWindow", "Laden", None))
        self.actionCal.setText(_translate("MainWindow", "Kalibrieren", None))

